name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: aneeshbhatnagar/cloudflare-ddns-updater:latest